### ISSUE TITLE
Missing partition table when writing iso image to usb flash drive

### ISSUE THREAD

**Issue by dean3518** [vanilla-dpup/releases#1]
Hi,

I downloaded a few different versions of the vanilladpupx86_64 image and tried to use Balena Etcher to write the image to a flash drive. When trying to flash from file Etcher gives an error message saying "Missing partition table, this image may not be bootable". How can this error be rectified? I am using the Linux version of Etcher as sudo. I would very much like to check out this new distro of Puppy, and the quicker this issue is resolved, the more people will want to download it and give it a try.
Thanks,
Dean Baker.

**Comment by dimkr** [comment]
Hi @dean3518!

1. Have you tried 9.2.x? 9.2.x is an ISO image while previous releases come as raw disk images and need to be ungzipped first, before you write them to the drive. To get the 9.2.7 ISO image, go to https://github.com/vanilla-dpup/releases/releases/download/vanilladpup-x86_64-9.2.7/vanilladpup-9.2.7.iso.
2. Make sure the downloaded ISO image size looks sane, it could be corrupt.

**Comment by dean3518** [comment]
Hi Dima,
Yes I have downloaded the latest version of the iso file, along with the version 9.2.6 all the way back to the version 9.0.6. All of the iso files have the same error when trying to write the disk image using Etcher. That error message says there's a partition table missing. Should I use another image writing tool or just dd the image straight to the flash drive?

**Comment by dimkr** [comment]
I use dd myself, I don't trust the GUI tools. Some of them are trying too hard to be user friendly.

**Comment by dean3518** [comment]
Hi Dima,
I will try to use the dd command. Thanks again for your help :)

**Comment by dimkr** [comment]
@dean3518 Can I close this one?

**Comment by dean3518** [comment]
Yes, you can. Thanks.
