### ISSUE TITLE
write 9.2.x iso to usb

### ISSUE THREAD

**Issue by Internet-viewer** [vanilla-dpup/releases#3]
Hi dimkr,
Thanks for releasing vanilla-dpup 9.2.x. It works amazing and I love its efficiency.
I have a small question on how to properly burn the iso to a bootable usb. I could only Rufus to write vanilladpup-9.2.10.iso to a usb (bootable). The problem is with file system, I can only choose fat32, which means the persistent storage can not go larger than 4GB. Also, each time it boots up, it shows something about iso9660 and need to pause for 60 seconds. I am wondering if you could give me some help on how to prepare a bootable usb properly. I tried the isohybrid and dd but no luck.

Thanks again.

**Comment by dimkr** [comment]
`dd` should work just fine. Try to `sync` before you unplug the flash drive and make sure it's not mounted before you start `dd`.

(I don't use tools like Rufus, because they're Windows-centric. I partition my flash drives manually with `fdisk` or `gdisk`, create an ext4 partition and install extlinux/efilinux.)

**Comment by Internet-viewer** [comment]
Hi, dimkr. Thanks for the rapid response. I just tried with dd and sync. Basically, `dd if=/path/to/vanilladpup-9.2.10.iso of=/dev/sdb1 && sync`. I am pretty sure the sdb1 is the partition to use. I formatted it to ext4 and did the above command. The partition was not mounted before dd. After the dd and sync, it seems that partition becomes ISO9660 format and is not bootable. I think I might have missed some steps here (maybe the extlinux/efilinux you mentioned?). Could you please give a more detail guidance?

**Comment by dimkr** [comment]
`of=/dev/sdb`, not `of=/dev/sdb1`. You should write to the device, not to a partition.

**Comment by dimkr** [comment]
To create a BIOS-bootable flash drive with one ext4 partition:

```
~$ fdisk /dev/sdb

Command (m for help): o
Building a new DOS disklabel. Changes will remain in memory only,
until you decide to write them. After that the previous content
won't be recoverable.


Command (m for help): n
Partition type
   p   primary partition (1-4)
   e   extended
p
Partition number (1-4): 1
First sector (22-1638399, default 22): 
Using default value 22
Last sector or +size{,K,M,G,T} (22-1638399, default 1638399): 
Using default value 1638399

Command (m for help): a
Partition number (1-4): 1
```

```
~$ mkfs.ext4 /dev/sdb1
mke2fs 1.46.5 (30-Dec-2021)
64-bit filesystem support is not enabled.  The larger fields afforded by this feature enable full-strength checksumming.  Pass -O 64bit to rectify.
Discarding device blocks: done                            
Creating filesystem with 204797 4k blocks and 51296 inodes
Filesystem UUID: a56d6489-c818-49e1-8a80-60d4255267b0
Superblock backups stored on blocks: 
	32768, 98304, 163840

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done
```

```
~$ mkdir /tmp/x
~$ mount /dev/sdb1 /tmp/x
~$ extlinux -i /tmp/x
/tmp/x is device /dev/loop7p1
Warning: unable to obtain device geometry (defaulting to 64 heads, 32 sectors)
         (on hard disks, this is usually harmless.)
~$ cat << EOF > /tmp/x/extlinux.conf
DEFAULT dpup
                                                
LABEL dpup
        LINUX vmlinuz           
        INITRD ucode.cpio,initrd.gz             
EOF
```

Then copy *.sfs, vmlinuz, initrd.gz and ucode.cpio from the ISO to /tmp/x.

Finally,

```
~$ umount /tmp/x
~$ sync
~$ eject /dev/sdb
```

**Comment by Internet-viewer** [comment]
Many thanks. I'll give it a go.

**Comment by dimkr** [comment]
@Internet-viewer Can I close this one?
