### ISSUE TITLE
Make memorystick boot vanilla using install script fails

### ISSUE THREAD

**Issue by mgrahamfa** [vanilla-dpup/releases#4]
Tried to make bootable memory stick using Puppy Installer.

it failed to boot.  It did not copy over menu.lst and grub.cfg, and it missed one of the sfs files, I think it was bdrv_vanilladpup_9.2.20.sfs

then it was able to boot.
I tried it a couple of ways, one time after booting from cdrom.

This is a great puppy!  keep up the good work!

**Comment by dimkr** [comment]
Yep, Puppy's installers are in a very sad, broken state 😿

**Comment by Littlemac123** [comment]
i hope it gets fixed, i wanted to try this out then saw grub is not just working out the box and was very confused trying to trouble shoot it

**Comment by dimkr** [comment]
At some point, I gave it a shot, but then gave up. When I offered users a basic installer that supports some use cases, they just ignored it.

It looks like Puppy users want a single solution that supports 1) installation alongside Windows 2) installation alongside other distros with either GRUB, GRUB or Grub4DOS 3) installation of Puppy with or without installation of the boot loader 4) installation on Windows file systems and 5) support for both BIOS and UEFI, with and without secure boot.

However, it also looks like Puppy users don't want a solution at all and prefer to tinker with their systems manually.

**Comment by mgrahamfa** [comment]
What I typically do is copy files from iso  to memory stick, and then run grub4dos  which does not seem to be available via apt install.  so I just used a different puppy, slacko, to do the grub4dos part.  However, I am seeing the need for eufi, so I guess I will need to look into other options.  Anyway, not finding grub4dos on vanillapup, first I tried the install option.  basically it just didn't copy some of the required files, and if I remember correctly, after copying them manually, it worked.  So I thought it would be a simple fix.  I have not looked into the script myself, but I guess from your comments, it's not so easy.  Don't give up on vanillapup, I really like it overall, and it is becoming my main system.

**Comment by dimkr** [comment]
> Don't give up on vanillapup

Don't worry, 10.0.x is on track :)

**Comment by mgrahamfa** [comment]
I decided I should write down exactly what I did to make the memory stick boot.
1. run puppy install from setup menu
2. pick boot flash installer
3. choose my usb memory stick
4. choose create grub4dos
5. choose ext3 partition and grub4dos  ...rest is from memory as I didn't want to do it again tonight.
6. when it asks after formatting, show it the iso which has to be the same as what is running (would be nice to be able to choose newer iso)
7. after it finished, try it.
8. missing menu.lst
9. add menu.lst, from one I had, and fixed it to add the cpio file (which was also missing). I noted the bdrv_vanilladpup_9.2.14.sfs was also missing, but at this point I tried without it.  here are the critical lines for the menu.lst:

title Puppy vanilladpup 9.2.14 (sdf1)
  root (hd0,0)
  kernel /vmlinuz     pmedia=usbflash pfix=fsck
  initrd /ucode.cpio /initrd.gz

after copying the cpio file to the memory stick, it booted.  On my daily user, I added the bdrv_vanilladpup_9.2.14.sfs  as I think it adds some drivers maybe....

hopefully this will help someone.

btw, i upgraded to 9.2.22 by copying files from iso over the ones on the memory stick.

so I am posting this stuff, because I really like this puppy, and would like to share with friends, but they would probably give up when things don't work.  maybe follow your format of most minimal, offering 1 item that works, and then add others as time permits.  thanks again.

a side note, I've gotten used to setting up a drive or memory stick with 2 or 3  or more versions of linux and letting grub4dos find them and add them to the menu.lst   I have been doing this booting from slacko7 , (and scpup)
I have not found any version of anything, linux or windows where everything works on 1 version, so having a few versions around works nicely for me.

**Comment by dimkr** [comment]
Fixed in 9.3.x and 10.0.x: bootflash works (https://github.com/puppylinux-woof-CE/woof-CE/pull/3700). Won't be fixed in 9.2.x.

**Comment by mgrahamfa** [comment]
Thanks!

    On Thursday, December 8, 2022, 06:59:15 AM UTC, Dima Krasner ***@***.***> wrote:  
 
 


Fixed in 9.3.x and 10.0.x: bootflash works (puppylinux-woof-CE/woof-CE#3700). Won't be fixed in 9.2.x.
