### ISSUE TITLE
Where is the project page?

### ISSUE THREAD

**Issue by lucmp** [vanilla-dpup/releases#5]
I know what Puppy Linux is but I don't really use it, I just thought I might soon and I can't remember why I subscribed to this version of Puppy specifically. Now I am trying to find the page that brought me here, I mean, the page where this Puppy remaster is described, including the differences in "retro," "xwayland" and the other. Can you please provide the link? TIA.

**Comment by dimkr** [comment]
Maybe https://vanilla-dpup.github.io/?

> this Puppy remaster

This is not a remaster 😠

**Comment by lucmp** [comment]
Thank you for the reply. That page helps, but I still can't decide on whether I should try the .iso or the retro.iso. The page won't clarify.

Maybe you could also let me know why my calling it a "remaster" made you angry. I honestly don't know what the correct term would be. I used Puppy once, but that was 12 years ago and I have forgotten many of the concepts.

One more thing, are there hashes I can get somewhere to verify the integrity of the download?

Thank you.

**Comment by dimkr** [comment]
> I still can't decide on whether I should try the .iso or the retro.iso. The page won't clarify.

If you're not sure or don't know what this small ISO is, you probably shouldn't use it. See https://forum.puppylinux.com/viewtopic.php?t=9113.

> One more thing, are there hashes I can get somewhere to verify the integrity of the download?

Nope.

**Comment by dimkr** [comment]
Closing, please use https://forum.puppylinux.com/viewforum.php?f=183 for questions and discussions.
